name: Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Send Telegram Notification
        uses: actions/telegram-notify@v1
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          text: "🚀 Repository ${GITHUB_REPOSITORY} received a new push on branch ${GITHUB_REF} by ${GITHUB_ACTOR}."
          parse_mode: markdown
          disable_web_page_preview: true
